### ISSUE TITLE
Using stdout.write sporadically causes output to not be flushed

### ISSUE THREAD

**Issue by lucascaro** [syumai/deno-libs#12]
Hi, I noticed that when asking for permissions sometimes the output gets weird and the program waits for input before displaying the output. I'm guessing this is the stdout.write not flushing before the read but I'm not sure...

**Comment by syumai** [comment]
I'll add output testing.
Please tell me about your environment (mac / linux / win)

**Comment by lucascaro** [comment]
oh yes, I saw this on mac. I haven't tested too much and it seems to happen when there are more than 3 flags... maybe?

**Comment by syumai** [comment]
OK, I'll check it later, thx!

**Comment by syumai** [comment]
Simply I'll use console.log

**Comment by lucascaro** [comment]
sounds good, the newline shouldn't be that big of a problem!
